version: '3.8'
services:
  web:
    build: .
    container_name: lucid_analytics_web
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - minio
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=EST
      - CHURN_MODEL_PATH=/app/models/churn_model_20250214_154838.pkl
      - CHURN_SCALER_PATH=/app/models/minmax_scaler.pkl
      - NPS_MODEL_PATH=/app/models/nps_model.pkl
      - NPS_SCALER_PATH=/app/models/nps_scaler.pkl
      - MEDIA_MODEL_PATH=/app/models/media_model_20250219_002020.pkl
      - MEDIA_SCALER_PATH=/app/models/standard_scaler.pkl
      - SITE_NAME=Lucid Analytics
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=marketing.models
      - MINIO_ASSET_BASE_URL=http://minio:9000/marketing.models/models/
      - MINIO_OBJECT_PREFIX=models/
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  minio-data:
