version: '3.8'

services:
  web:
    build: .
    container_name: lucid_analytics_web
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - minio
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      TZ: "EST"
      CHURN_MODEL_PATH: "/app/models/churn_model_20250214_154838.pkl"
      CHURN_SCALER_PATH: "/app/models/minmax_scaler.pkl"
      NPS_MODEL_PATH: "/app/models/nps_model.pkl"
      NPS_SCALER_PATH: "/app/models/nps_scaler.pkl"
      MEDIA_MODEL_PATH: "/app/models/media_model_20250219_002020.pkl"
      MEDIA_SCALER_PATH: "/app/models/standard_scaler.pkl"
      SITE_NAME: "Lucid Analytics"
      MINIO_BASE_URL: "https://lucidanalytics-production.up.railway.app/marketing.models/models/"
      MINIO_ENDPOINT: "lucidanalytics-production.up.railway.app"
      MINIO_USE_SSL: "true"
      MINIO_OBJECT_PREFIX: "models/"
    # Code is embedded in the image; removed volume mounts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: .
    container_name: lucid_analytics_worker
    restart: always
    working_dir: /app
    command: celery -A utils.tasks.celery_app worker --loglevel=info
    depends_on:
      - minio
      - redis
    environment:
      # Use the same Redis connection as the web service
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      TZ: "EST"
      CHURN_MODEL_PATH: "/app/models/churn_model_20250220_182726.pkl"
      CHURN_SCALER_PATH: "/app/models/minmax_scaler.pkl"
      NPS_MODEL_PATH: "/app/models/nps_model.pkl"
      NPS_SCALER_PATH: "/app/models/nps_scaler.pkl"
      MEDIA_MODEL_PATH: "/app/models/media_model_20250219_002020.pkl"
      MEDIA_SCALER_PATH: "/app/models/standard_scaler.pkl"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "marketing.models"
      MINIO_OBJECT_PREFIX: "models/"
      SITE_NAME: "Lucid Analytics"
    # Code is embedded in the image; removed volume mounts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "celery", "-A", "utils.tasks.celery_app", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ENDPOINT: "lucidanalytics-production.up.railway.app"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "marketing.models"
      MINIO_BASE_URL: "https://lucidanalytics-production.up.railway.app/marketing.models/models/"
      MINIO_OBJECT_PREFIX: "models/"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio-data:

networks:
  app-network:
